# Generated by Django 4.1.1 on 2022-10-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_image_prod_stockproducts_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproducts',
            name='cant_prod',
        ),
        migrations.AddField(
            model_name='stockproducts',
            name='hayStock',
            field=models.BooleanField(default=True),
        ),
    ]
