# Generated by Django 4.1.1 on 2022-10-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_stockproducts_cant_prod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproducts',
            name='hayStock',
        ),
    ]
