# Generated by Django 4.1.1 on 2022-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_stockproducts_haystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproducts',
            name='hayStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockproducts',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
