# Generated by Django 4.1.1 on 2022-11-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_stockproducts_haystock_alter_stockproducts_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.stockproducts'),
        ),
    ]
