# Generated by Django 4.1.1 on 2022-11-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_carrito_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
