# Generated by Django 4.1.1 on 2022-11-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_pedidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pedidos',
        ),
    ]
