# Generated by Django 4.1.1 on 2022-11-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_rename_telfono_pedidos_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido',
        ),
    ]
