# Generated by Django 4.1.1 on 2022-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_remove_compra_direccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='apellido_cliente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='codigo_estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='correo_cliente',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_cliente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_cliente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_de_la_compra',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
