# Generated by Django 4.1.1 on 2022-11-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_compra_apellido_cliente_compra_codigo_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
