# Generated by Django 4.1.1 on 2022-12-10 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_valoraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.carrito'),
        ),
    ]
