# Generated by Django 4.1.1 on 2022-12-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_pedidos_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cart',
        ),
    ]
