# Generated by Django 4.1.1 on 2022-12-10 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_remove_pedidos_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='idPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedidos'),
        ),
    ]
