# Generated by Django 4.1.1 on 2022-12-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_carrito_idpedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idPedido',
        ),
    ]
