# Generated by Django 4.1.1 on 2022-12-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0025_remove_carrito_idpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='productoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_pedido', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedidos')),
                ('producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.stockproducts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
