# Generated by Django 4.1.1 on 2022-12-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_productopedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carrito',
        ),
    ]
