# Generated by Django 4.1.4 on 2022-12-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodsPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos')),
                ('producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.stockproducts')),
            ],
        ),
    ]
