# Generated by Django 4.1.4 on 2022-12-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_prodspedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodspedidos',
            name='pedido_id',
            field=models.IntegerField(null=True),
        ),
    ]
