# Generated by Django 4.1.4 on 2022-12-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_prodspedidos_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodspedidos',
            name='producto_id',
            field=models.IntegerField(null=True),
        ),
    ]
