# Generated by Django 4.1.4 on 2022-12-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('pedidos', '0005_alter_prodspedidos_pedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodspedidos',
            name='producto_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
