# Generated by Django 4.1.4 on 2022-12-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0006_alter_prodspedidos_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodspedidos',
            name='producto_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.stockproducts'),
        ),
    ]
