# Generated by Django 4.1.1 on 2022-12-11 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0027_delete_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('nom_prod', models.TextField(max_length=200)),
                ('cant_prod', models.IntegerField()),
                ('precio_prod', models.FloatField()),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.stockproducts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
