# Generated by Django 4.1.4 on 2022-12-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(null=True, upload_to='products')),
                ('nom_prod', models.CharField(max_length=50)),
                ('precio_prod', models.FloatField()),
                ('descripcion', models.TextField(max_length=250)),
                ('hayStock', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categorias')),
            ],
        ),
    ]
